export const elements = {
    questArea: document.getElementById("questionArea"),
    answerKeyArea: document.getElementById("answerKeyArea"),
    nameArea: document.getElementById("setNameArea"),
    submitQuestions: document.getElementById("submit"),
    checkAnsBut: document.querySelector(".checkAnsBut"),
    addQuizBut: document.querySelector(".addQuizBut"),
    nextBut: document.querySelector(".nextBut"),
    prevBut: document.querySelector(".prevBut"),
    getQuestionsArea: document.querySelector(".get_questions-container"),
    setChoicesArea: document.querySelector(".set_choices-container"),
    setButtonsContainer: document.querySelector(".setButtonContainers"),
    questSetContainer: document.querySelector(".questSet-container"),
    setCardOptions: document.querySelector(".setCard_options"),
    setCardDropdown: document.querySelector(".options_dropdown"),
    quizContainer: document.querySelector(".quiz-container"),
    progressSteps: document.getElementsByClassName('step'),
    displayQuestions: document.querySelector(".displayQuestions"),
    questionNumber: document.querySelector(".questionNumber-container"),
    questionContainer: document.querySelector(".question-container"),
    choicesContainer: document.querySelector(".choices-container"),
    inputChoices: document.getElementsByTagName('input'),
    finishedContainer: document.querySelector(".finishedQuiz_container")
}